export const COMMON_MEDICATIONS = [
  { name: "Paracetamol", unit: "Tablet", category: "Analgesic" },
  { name: "Ibuprofen", unit: "Tablet", category: "NSAID" },
  { name: "Amoxicillin", unit: "Capsule", category: "Antibiotic" },
  { name: "Cetirizine", unit: "Tablet", category: "Antihistamine" },
  { name: "Omeprazole", unit: "Capsule", category: "PPI" },
  { name: "Metformin", unit: "Tablet", category: "Antidiabetic" },
  { name: "Amlodipine", unit: "Tablet", category: "Antihypertensive" },
  { name: "Atorvastatin", unit: "Tablet", category: "Statin" },
  { name: "Salbutamol", unit: "Inhaler", category: "Bronchodilator" },
  { name: "Prednisolone", unit: "Tablet", category: "Corticosteroid" },
  { name: "Aspirin", unit: "Tablet", category: "Antiplatelet" },
  { name: "Cough Syrup", unit: "Syrup", category: "Antitussive" },
  { name: "Vitamin D3", unit: "Tablet", category: "Vitamin" },
  { name: "Iron Supplement", unit: "Tablet", category: "Mineral" },
  { name: "Calcium", unit: "Tablet", category: "Mineral" },
]

export const COMMON_DIAGNOSES = [
  "Upper Respiratory Tract Infection",
  "Viral Fever",
  "Hypertension",
  "Type 2 Diabetes Mellitus",
  "Gastroesophageal Reflux Disease",
  "Allergic Rhinitis",
  "Bronchial Asthma",
  "Urinary Tract Infection",
  "Migraine",
  "Lower Back Pain",
  "Anxiety Disorder",
  "Depression",
  "Osteoarthritis",
  "Hyperlipidemia",
  "Chronic Obstructive Pulmonary Disease",
]

export const COMMON_DIETS = [
  "Increase fluid intake",
  "Avoid spicy foods",
  "Low sodium diet",
  "Diabetic diet",
  "High fiber diet",
  "Avoid dairy products",
  "Bland diet",
  "Increase protein intake",
  "Avoid alcohol",
  "Small frequent meals",
  "Avoid caffeine",
  "Mediterranean diet",
]

export const DOSAGE_FREQUENCIES = [
  "Once daily",
  "Twice daily",
  "Three times daily",
  "Four times daily",
  "Every 4 hours",
  "Every 6 hours",
  "Every 8 hours",
  "Every 12 hours",
  "As needed",
  "Before meals",
  "After meals",
  "At bedtime",
]

export const MEDICATION_UNITS = [
  "Tablet",
  "Capsule",
  "Syrup",
  "Injection",
  "Drops",
  "Cream",
  "Ointment",
  "Inhaler",
  "Patch",
  "Suppository",
  "Powder",
  "Solution",
]
