export const doctorsData = [
  {
    id: "doc1",
    name: "Dr. Emily White",
    specialty: "Cardiology",
    experience: "10+ Yrs",
    contact: "+91 98765 43210",
    reviews: 258,
    rating: 4,
    location: "New Delhi",
    doctorinfo: {
      presentaddress: "Delhi, India",
      consultationfee: 1000,
      profiledescription: "Dr. Emily White is a well-respected cardiologist...",
      passportphoto: "",
      homehealthcarevisit: true,
    },
    consultationFee: {
      original: 1200,
      discounted: 1000,
    },
    tieUpHospitals: "05+",
    patients: "1000+",
    homeHealthcare: true,
    profileInfo:
      "Dr. Emily White is a highly experienced cardiologist with over 10 years of practice. She specializes in diagnosing and treating heart conditions, providing comprehensive care to her patients.",
  },
  {
    id: "doc2",
    name: "Dr. John Doe",
    specialty: "Pediatrics",
    experience: "07+ Yrs",
    contact: "+91 98765 12345",
    reviews: 580,
    rating: 5,
    location: "Mumbai",
    doctorinfo: {
      presentaddress: "Mumbai, India",
      consultationfee: 1200,
      profiledescription: "Dr. John Doe is known for pediatric excellence...",
      passportphoto: "",
      homehealthcarevisit: false,
    },
    consultationFee: {
      original: 1500,
      discounted: 1200,
    },
    tieUpHospitals: "08+",
    patients: "1500+",
    homeHealthcare: false,
    profileInfo:
      "Dr. John Doe is a dedicated pediatrician with 7 years of experience in child healthcare. He provides expert care for infants and adolescents.",
  },
  {
    id: "doc3",
    name: "Dr. Sarah Lee",
    specialty: "Dermatology",
    experience: "09+ Yrs",
    contact: "+91 98765 67890",
    reviews: 351,
    rating: 4,
    location: "Bangalore",
    doctorinfo: {
      presentaddress: "Bangalore, India",
      consultationfee: 900,
      profiledescription: "Dr. Sarah Lee is a specialist in dermatology...",
      passportphoto: "",
      homehealthcarevisit: true,
    },
    consultationFee: {
      original: 1100,
      discounted: 900,
    },
    tieUpHospitals: "04+",
    patients: "800+",
    homeHealthcare: true,
    profileInfo:
      "Dr. Sarah Lee is a renowned dermatologist offering treatment for skin, hair, and nail conditions with a personalized approach.",
  },
  {
    id: "doc4",
    name: "Dr. Alex Chen",
    specialty: "Orthopedics",
    experience: "12+ Yrs",
    contact: "+91 98765 09876",
    reviews: 183,
    rating: 3,
    location: "Chennai",
    doctorinfo: {
      presentaddress: "Chennai, India",
      consultationfee: 1100,
      profiledescription: "Dr. Alex Chen specializes in joint and bone care...",
      passportphoto: "",
      homehealthcarevisit: false,
    },
    consultationFee: {
      original: 1300,
      discounted: 1100,
    },
    tieUpHospitals: "06+",
    patients: "1200+",
    homeHealthcare: false,
    profileInfo:
      "Dr. Alex Chen is an orthopedic surgeon known for joint replacements and sports injury treatment with 12 years of expertise.",
  },
  {
    id: "doc5",
    name: "Dr. Ayesha Singh",
    specialty: "Gastroenterology",
    experience: "11+ Yrs",
    contact: "+91 98765 24680",
    reviews: 219,
    rating: 4,
    location: "Hyderabad",
    doctorinfo: {
      presentaddress: "Hyderabad, India",
      consultationfee: 950,
      profiledescription: "Dr. Ayesha is known for digestive disorder treatments...",
      passportphoto: "",
      homehealthcarevisit: true,
    },
    consultationFee: {
      original: 1200,
      discounted: 950,
    },
    tieUpHospitals: "03+",
    patients: "950+",
    homeHealthcare: true,
    profileInfo:
      "Dr. Ayesha Singh provides expert care in gastrointestinal issues including liver, pancreas, and colon disorders.",
  },
  {
    id: "doc6",
    name: "Dr. Raj Mehta",
    specialty: "Neurology",
    experience: "14+ Yrs",
    contact: "+91 98765 13579",
    reviews: 410,
    rating: 5,
    location: "Pune",
    doctorinfo: {
      presentaddress: "Pune, India",
      consultationfee: 1300,
      profiledescription: "Dr. Raj Mehta is a senior neurologist...",
      passportphoto: "",
      homehealthcarevisit: false,
    },
    consultationFee: {
      original: 1500,
      discounted: 1300,
    },
    tieUpHospitals: "07+",
    patients: "1700+",
    homeHealthcare: false,
    profileInfo:
      "Dr. Raj Mehta is a leading neurologist treating epilepsy, stroke, and neurodegenerative conditions for over 14 years.",
  },
]
